<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AdministracaoCliente" targetNamespace="http://workshop.com.br/ClienteService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://workshop.com.br/ClienteService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="AdministracaoCliente_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="AdministracaoClienteSOAP" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  <wsdl:types>
    <xsd:schema targetNamespace="http://workshop.com.br/ClienteService" xmlns:pref="http://workshop.com.br/schemas/cliente">
<xsd:import namespace="http://workshop.com.br/schemas/cliente" schemaLocation="schemas/Cliente.xsd"/>
<xsd:include schemaLocation="AdministracaoCliente_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="consultarClienteRequest">
    <wsdl:part element="tns:consultarCliente" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="consultarClienteResponse">
    <wsdl:part element="tns:consultarClienteResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="AdministracaoCliente">
    <wsdl:operation name="consultarCliente">
      <wsdl:input message="tns:consultarClienteRequest"/>
      <wsdl:output message="tns:consultarClienteResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AdministracaoClienteSOAP" type="tns:AdministracaoCliente">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="consultarCliente">
      <soap:operation soapAction="http://workshop.com.br/ClienteService/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AdministracaoCliente">
    <wsdl:port binding="tns:AdministracaoClienteSOAP" name="AdministracaoClienteSOAP">
      <soap:address location="http://localhost:7800/ClienteService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>